version: 2
updates:
  - package-ecosystem: npm
    directory: "/cli"
    schedule:
      interval: weekly
    labels:
      - dependencies
      - cli

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
    labels:
      - dependencies
      - ci
